import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { cn } from '@/lib/utils'
import { SiteHeader } from '@/components/site-header'
import { ShoppingCartProvider } from '@/components/shopping-cart'
import { Toaster } from '@/components/ui/toaster'

import '@/styles/globals.css'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          inter.variable,
        )}
      >
        <div className="relative flex min-h-screen flex-col">
          <ShoppingCartProvider>
            <SiteHeader />
            <div className="mt-6 flex-1">{children}</div>
            <Toaster />
          </ShoppingCartProvider>
        </div>
      </body>
    </html>
  )
}
